// ============================================================
// FLASHCARD DATA — Afrikaans Grade 12 CAPS
// ============================================================
const flashcards = [
    // --- Begrip en Opsomming (Comprehension & Summary) ---
    { id: 1, unit: "begrip", q: "Wat is die verskil tussen begrip (comprehension) en opsomming (summary)?", a: "Begrip toets jou vermoë om 'n teks te verstaan en vrae daaroor te beantwoord. Opsomming vereis dat jy die hoofpunte van 'n teks in 'n beperkte aantal woorde saamvat (summarise the main points in limited words)." },
    { id: 2, unit: "begrip", q: "Noem 5 leesstrategie\u00eb (reading strategies) vir begrip.", a: "1. Skandeer (scan) vir spesifieke inligting\n2. Vlugtig lees (skim) vir hoofgedagte\n3. Intensiewe lees (intensive reading) vir detail\n4. Kontekstuele leidrade (contextual clues) vir woordbetekenis\n5. Voorspelling (prediction) \u2014 raai wat volgende kom" },
    { id: 3, unit: "begrip", q: "Wat is 'n hoofgedagte (main idea) en hoe identifiseer jy dit?", a: "Die hoofgedagte is die sentrale boodskap van 'n paragraaf of teks. Dit word gewoonlik in die eerste of laaste sin gevind. Vra jouself: 'Waaroor gaan hierdie paragraaf hoofsaaklik?'" },
    { id: 4, unit: "begrip", q: "Hoe beantwoord jy 'n sitaatvraag (quote question) in begrip?", a: "1. Lees die vraag noukeurig\n2. Vind die sitaat in die teks\n3. Lees die konteks rondom die sitaat\n4. Beantwoord in jou eie woorde (answer in your own words)\n5. Gebruik aanhalingstekens as jy direk aanhaal" },
    { id: 5, unit: "begrip", q: "Wat is die re\u00ebls vir 'n opsomming (summary rules)?", a: "1. Lees die teks deeglik\n2. Identifiseer die hoofpunte (main points)\n3. Skryf in jou eie woorde\n4. Hou by die woordgrens (word limit) \u2014 gewoonlik 70 woorde\n5. Tel jou woorde en skryf die getal neer\n6. Moenie voorbeelde of herhalings insluit nie\n7. Skryf in een paragraaf, volsinne" },
    { id: 6, unit: "begrip", q: "Wat beteken 'in jou eie woorde' (in your own words)?", a: "Dit beteken jy moet die inligting herformuleer (paraphrase) \u2014 gebruik sinonieme en verander die sinstruktuur. Moenie net woorde uit die teks kopieer nie." },
    { id: 7, unit: "begrip", q: "Noem 4 tipes begripsvrae (types of comprehension questions).", a: "1. Letterlike vrae (literal) \u2014 antwoord direk in die teks\n2. Inferensi\u00eble vrae (inferential) \u2014 afleidings maak\n3. Evaluerende vrae (evaluative) \u2014 jou mening gee\n4. Taalvrae (language) \u2014 woordbetekenis, figuurlike taal" },
    { id: 8, unit: "begrip", q: "Hoe hanteer jy woordeskatvrae (vocabulary questions) in begrip?", a: "1. Lees die sin waarin die woord voorkom\n2. Gebruik kontekstuele leidrade (context clues)\n3. Kyk na voor- en agtervoegsels (prefixes/suffixes)\n4. Gee 'n sinoniem of omskrywing\n5. Maak seker jou antwoord pas in die konteks" },
    { id: 9, unit: "begrip", q: "Wat is die verskil tussen 'n feit (fact) en 'n mening (opinion)?", a: "Feit: kan bewys word as waar of vals \u2014 bv. 'Suid-Afrika het 11 amptelike tale.'\nMening: 'n persoonlike siening wat nie bewys kan word nie \u2014 bv. 'Afrikaans is die mooiste taal.'" },
    { id: 10, unit: "begrip", q: "Hoe identifiseer jy die skrywer se doel (author's purpose)?", a: "Vra: Wil die skrywer\n1. Inlig (inform) \u2014 feite en inligting gee\n2. Oorreed (persuade) \u2014 die leser oortuig\n3. Vermaak (entertain) \u2014 die leser vermaak\n4. Onderrig (instruct) \u2014 stappe of instruksies gee\nKyk na taalgebruik, toon, en inhoud vir leidrade." },
    // --- Gedigte (Poetry) ---
    { id: 11, unit: "gedigte", q: "Wat is beeldspraak (figurative language)?", a: "Beeldspraak is taal wat nie letterlik bedoel word nie. Dit skep beelde in die leser se gedagtes. Voorbeelde: metafoor, vergelyking, personifikasie." },
    { id: 12, unit: "gedigte", q: "Wat is die verskil tussen 'n metafoor (metaphor) en 'n vergelyking (simile)?", a: "Metafoor: direkte vergelyking SONDER 'soos' of 'net soos' \u2014 bv. 'Die lewe is 'n reis.'\nVergelyking (simile): vergelyking MET 'soos' of 'net soos' \u2014 bv. 'Sy lag soos 'n klokkie.'" },
    { id: 13, unit: "gedigte", q: "Wat is personifikasie (personification)?", a: "Personifikasie is wanneer menslike eienskappe aan nie-menslike dinge toegeken word. Bv. 'Die wind fluister' (the wind whispers) \u2014 wind kan nie regtig fluister nie." },
    { id: 14, unit: "gedigte", q: "Wat is alliterasie (alliteration)?", a: "Alliterasie is die herhaling van dieselfde konsonantklank (consonant sound) aan die begin van opeenvolgende of nabyliggende woorde. Bv. 'Die donker dae van droogte.'" },
    { id: 15, unit: "gedigte", q: "Wat is assonansie (assonance)?", a: "Assonansie is die herhaling van vokaalklank (vowel sounds) binne woorde naby mekaar. Bv. 'Die lig skyn oor die wye veld.'" },
    { id: 16, unit: "gedigte", q: "Noem die verskillende rymtipes (types of rhyme).", a: "1. Eindrym (end rhyme): woorde aan die einde van re\u00ebls rym\n2. Kruisrym (cross rhyme): ABAB-patroon\n3. Paarrym (couplet rhyme): AABB-patroon\n4. Omarmde rym (enclosed rhyme): ABBA-patroon\n5. Binnerym (internal rhyme): rym binne dieselfde re\u00ebl" },
    { id: 17, unit: "gedigte", q: "Wat is 'n strofe (stanza) en 'n versre\u00ebl (line)?", a: "Strofe (stanza): 'n groep versre\u00ebls wat saam hoort, geskei deur wit spasie \u2014 soos 'n paragraaf in prosa.\nVersre\u00ebl (line): een re\u00ebl van die gedig." },
    { id: 18, unit: "gedigte", q: "Wat is enjambement (enjambment)?", a: "Enjambement is wanneer 'n sin oor die einde van 'n versre\u00ebl na die volgende re\u00ebl voortvloei sonder leesteken. Dit skep 'n vloeiende ritme en beklemtoon sekere woorde." },
    { id: 19, unit: "gedigte", q: "Hoe analiseer jy 'n gedig se toon (tone) en bui (mood)?", a: "Toon (tone): die digter se houding teenoor die onderwerp \u2014 bv. hartseer, kwaad, speels.\nBui (mood): die gevoel wat die gedig by die leser skep \u2014 bv. somber, vrolik.\nKyk na woordkeuse (diction), beeldspraak, en klankeffekte vir leidrade." },
    { id: 20, unit: "gedigte", q: "Wat is 'n tema (theme) in 'n gedig?", a: "Die tema is die sentrale boodskap of onderwerp van die gedig \u2014 bv. liefde, dood, natuur, eensaamheid, identiteit. Dit is nie 'n opsomming nie, maar die dieper betekenis." },
    { id: 21, unit: "gedigte", q: "Hoe struktureer jy 'n gedigvraag-antwoord in die eksamen?", a: "1. Noem die digterlike tegniek (poetic device)\n2. Haal aan uit die gedig (quote from poem)\n3. Verduidelik die effek (explain the effect)\n4. Koppel dit aan die tema of boodskap\nFormule: TEGNIEK + AANHALING + EFFEK + TEMA" },
    { id: 22, unit: "gedigte", q: "Wat is 'n hiperbool (hyperbole)?", a: "Hiperbool is 'n oordrywing (exaggeration) wat gebruik word vir effek of klem. Bv. 'Ek het 'n miljoen keer ges\u00ea' of 'Ek is so honger ek kan 'n perd eet.'" },
    { id: 23, unit: "gedigte", q: "Wat is onomatopee (onomatopoeia)?", a: "Onomatopee is wanneer 'n woord soos die klank klink wat dit beskryf. Bv. 'sis', 'brom', 'kraak', 'druppel'. Dit skep klankeffekte en maak die gedig meer lewendig." },
    { id: 24, unit: "gedigte", q: "Wat is ironie (irony) in po\u00ebsie?", a: "Ironie is wanneer die teenoorgestelde van wat verwag word, gebeur of ges\u00ea word.\nVerbale ironie: jy s\u00ea die teenoorgestelde van wat jy bedoel.\nSituasionele ironie: die uitkoms is anders as wat verwag is.\nDramatiese ironie: die leser weet iets wat 'n karakter nie weet nie." },
    { id: 25, unit: "gedigte", q: "Wat is die verskil tussen vrye vers (free verse) en vaste versvorme?", a: "Vrye vers: geen vaste rymskema of metrum nie \u2014 die digter kies self die struktuur.\nVaste versvorme: volg vasgestelde re\u00ebls vir rym, metrum, en strofes \u2014 bv. sonnet (14 re\u00ebls)." },
    // --- Skryfwerk (Writing) ---
    { id: 26, unit: "skryfwerk", q: "Wat is die struktuur van 'n opstel (essay structure)?", a: "1. Inleiding (introduction): vang aandag, stel onderwerp voor\n2. Liggaam (body): 3\u20135 paragrawe met hoofpunte en voorbeelde\n3. Slot (conclusion): som op, gee finale gedagte\nElke paragraaf het 'n topiksin (topic sentence), ondersteuning, en 'n slotsin." },
    { id: 27, unit: "skryfwerk", q: "Wat is die verskil tussen 'n formele (formal) en informele (informal) brief?", a: "Formele brief: saaklike taal, volledige adres, 'Geagte Mnr./Mev.', 'Die uwe'\nInformele brief: vriendskaplike taal, net jou adres, 'Liewe [naam]', 'Liefde/Groete'\nFormeel = aan vreemdelinge/amptelik. Informeel = aan vriende/familie." },
    { id: 28, unit: "skryfwerk", q: "Noem die formaat van 'n formele brief (formal letter format).", a: "1. Jou adres (regs bo)\n2. Datum\n3. Ontvanger se adres (links)\n4. Aanhef: 'Geagte Mnr./Mev. [Van]'\n5. Onderwerpreël (subject line)\n6. Liggaam van brief\n7. Groet: 'Die uwe' (Yours faithfully/sincerely)\n8. Handtekening en naam" },
    { id: 29, unit: "skryfwerk", q: "Hoe skryf jy 'n goeie inleiding (introduction) vir 'n opstel?", a: "Strategie\u00eb:\n1. Begin met 'n vraag (rhetorical question)\n2. Begin met 'n aanhaling (quote)\n3. Begin met 'n stelling (bold statement)\n4. Begin met 'n anekdote (short story)\n5. Skets die agtergrond\nDie inleiding moet die leser se aandag vang en die onderwerp bekendstel." },
    { id: 30, unit: "skryfwerk", q: "Wat is 'n artikel (article) se formaat?", a: "1. Pakkende opskrif (catchy headline)\n2. Subtitel of byskrif (optional)\n3. Inleiding \u2014 wie, wat, waar, wanneer, waarom\n4. Liggaam \u2014 besonderhede, aanhalings, feite\n5. Slot \u2014 opsomming of oproep tot aksie\nSkryf in kolomme-styl, kort paragrawe." },
    { id: 31, unit: "skryfwerk", q: "Wat is die kenmerke van 'n dialoog (dialogue)?", a: "1. Gebruik aanhalingstekens (quotation marks)\n2. Elke spreker se woorde begin op 'n nuwe re\u00ebl\n3. Gebruik s\u00ea-werkwoorde (said-verbs): s\u00ea, vra, antwoord, fluister, skree\n4. Sluit toneelaanwysings in (stage directions): liggaamstaal, emosie\n5. Moet natuurlik klink" },
    { id: 32, unit: "skryfwerk", q: "Wat is die verskil tussen beskrywende (descriptive) en argumentatiewe (argumentative) skryfwerk?", a: "Beskrywend: gebruik sintuie (senses) om 'n prentjie te skep \u2014 sien, hoor, ruik, voel, proe. Doel: laat die leser dit ervaar.\nArgumentatief: neem 'n standpunt in en oortuig die leser met redes, feite, en voorbeelde. Doel: oortuig (persuade)." },
    { id: 33, unit: "skryfwerk", q: "Noem 5 tipes skryfwerk in die Afrikaans-eksamen.", a: "1. Opstel (essay) \u2014 narratief, beskrywend, of argumentatief\n2. Formele brief (formal letter)\n3. Informele brief (informal/friendly letter)\n4. Artikel (article)\n5. Dialoog (dialogue)\n6. Dagboekinskrywing (diary entry)\n7. Toespraak (speech)" },
    { id: 34, unit: "skryfwerk", q: "Hoe skryf jy 'n argumentatiewe opstel (argumentative essay)?", a: "1. Inleiding: stel die kwessie (issue) en jou standpunt (stance)\n2. Argument 1 + bewys (evidence)\n3. Argument 2 + bewys\n4. Teenargument (counter-argument) en weerlegging (rebuttal)\n5. Slot: herbevestig jou standpunt, oproep tot aksie\nGebruik verbindingswoorde: daarom, gevolglik, aan die ander kant" },
    { id: 35, unit: "skryfwerk", q: "Wat is verbindingswoorde (connectives/linking words)? Gee voorbeelde.", a: "Verbindingswoorde verbind idees en sinne:\n- Byvoeging: ook, boonop, verder, daarbenewens (also, moreover)\n- Kontras: maar, egter, nogtans (but, however)\n- Oorsaak: omdat, want, aangesien (because, since)\n- Gevolg: daarom, gevolglik, dus (therefore)\n- Tyd: eerstens, daarna, ten slotte (firstly, then, finally)" },
    { id: 36, unit: "skryfwerk", q: "Wat is die assesseringskriteria (assessment criteria) vir skryfwerk?", a: "1. Inhoud en beplanning (content & planning) \u2014 30 punte\n2. Taal, styl en redigering (language, style & editing) \u2014 15 punte\n3. Struktuur (structure) \u2014 5 punte\nTotaal: 50 punte." },
    { id: 37, unit: "skryfwerk", q: "Hoe skryf jy 'n dagboekinskrywing (diary entry)?", a: "1. Datum regbo\n2. Aanhef: 'Liewe Dagboek' (Dear Diary)\n3. Skryf in eerste persoon (ek/my)\n4. Deel gedagtes, gevoelens, en ervarings\n5. Informele, persoonlike toon\n6. Slot: 'Tot m\u00f4re' of soortgelyk" },
    { id: 38, unit: "skryfwerk", q: "Wat is register (register) in taalgebruik?", a: "Register is die vlak van formaliteit in jou taalgebruik.\nFormeel: saaklik, beleefd, geen sleng \u2014 bv. formele brief, toespraak\nInformeel: vriendskaplik, ontspanne, sleng toegelaat \u2014 bv. informele brief, dialoog\nJy moet die regte register vir die situasie kies." },
    { id: 39, unit: "skryfwerk", q: "Hoe beplan jy 'n opstel voor jy begin skryf?", a: "1. Lees die onderwerp noukeurig\n2. Brainstorm idees (dinkskrum)\n3. Maak 'n gedagtekart (mind map) of lys\n4. Organiseer idees in logiese volgorde\n5. Skryf 'n kort raamwerk: inleiding, liggaam (3-5 punte), slot\n6. Begin skryf en hou by jou plan" },
    { id: 40, unit: "skryfwerk", q: "Wat is 'n toespraak (speech) se formaat?", a: "1. Aanhef: 'Geagte [gehoor]' of 'Dames en Here'\n2. Inleiding: stel onderwerp voor, vang aandag\n3. Liggaam: hoofpunte met voorbeelde\n4. Slot: opsomming, oproep tot aksie\n5. Retoriese vrae en herhalings vir effek\n6. Direkte aanspreekvorm ('julle', 'ons')" }
];

// ============================================================
// QUIZ QUESTIONS \u2014 Afrikaans Grade 12 CAPS
// ============================================================
const quizQuestions = [
    // --- Begrip en Opsomming ---
    { id: 1, unit: "begrip", type: "mc", question: "Wat is die woordlimiet vir 'n opsomming in die Afrikaans-eksamen?", options: ["50 woorde", "70 woorde", "100 woorde", "90 woorde"], correct: 1, explanation: "Die opsomming moet gewoonlik in 70 woorde of minder geskryf word. Jy moet jou woorde tel en die getal neerskryf." },
    { id: 2, unit: "begrip", type: "mc", question: "'n Inferensi\u00eble vraag (inferential question) vereis dat jy:", options: ["Die antwoord direk uit die teks haal", "Afleidings maak uit die teks (make inferences)", "Jou persoonlike mening gee", "Die taal van die teks analiseer"], correct: 1, explanation: "Inferensi\u00eble vrae vereis dat jy afleidings maak \u2014 die antwoord staan nie direk in die teks nie, maar jy moet dit aflei uit die konteks." },
    { id: 3, unit: "begrip", type: "mc", question: "Watter strategie gebruik jy om vinnig spesifieke inligting in 'n teks te vind?", options: ["Intensiewe lees", "Skandeer (scanning)", "Vlugtig lees (skimming)", "Krities lees"], correct: 1, explanation: "Skandeer (scanning) is wanneer jy soek na spesifieke inligting soos 'n naam, datum, of syfer sonder om die hele teks te lees." },
    { id: 4, unit: "begrip", type: "mc", question: "In 'n opsomming mag jy NIE die volgende doen nie:", options: ["In jou eie woorde skryf", "Voorbeelde en herhalings insluit", "Volsinne gebruik", "Die hoofpunte identifiseer"], correct: 1, explanation: "In 'n opsomming moet jy voorbeelde, herhalings, en onnodige besonderhede weglaat. Fokus net op die hoofpunte." },
    { id: 5, unit: "begrip", type: "mc", question: "Wat beteken dit om 'kontekstuele leidrade' (context clues) te gebruik?", options: ["Die woordeboek gebruik", "Die omliggende woorde en sinne gebruik om betekenis af te lei", "Die titel van die teks lees", "Die skrywer se biografie lees"], correct: 1, explanation: "Kontekstuele leidrade beteken jy gebruik die woorde en sinne rondom 'n onbekende woord om die betekenis daarvan af te lei." },
    { id: 6, unit: "begrip", type: "mc", question: "Die hoofgedagte van 'n paragraaf word gewoonlik gevind in die:", options: ["Middel van die paragraaf", "Eerste of laaste sin", "Titel van die teks", "Voetnote"], correct: 1, explanation: "Die hoofgedagte (main idea) word gewoonlik in die eerste sin (topiksin) of laaste sin van 'n paragraaf gevind." },
    // --- Gedigte ---
    { id: 7, unit: "gedigte", type: "mc", question: "'Die son lag vir die w\u00eareld' is 'n voorbeeld van:", options: ["Metafoor", "Vergelyking", "Personifikasie", "Alliterasie"], correct: 2, explanation: "Dit is personifikasie omdat die son (nie-menslik) 'n menslike handeling (lag) toegeken word." },
    { id: 8, unit: "gedigte", type: "mc", question: "'Sy o\u00eb is sterre' is 'n voorbeeld van 'n:", options: ["Vergelyking (simile)", "Metafoor (metaphor)", "Personifikasie", "Hiperbool"], correct: 1, explanation: "Dit is 'n metafoor omdat dit 'n direkte vergelyking maak SONDER 'soos' of 'net soos'. Sy o\u00eb WORD sterre genoem." },
    { id: 9, unit: "gedigte", type: "mc", question: "Wat is kruisrym (cross rhyme)?", options: ["AABB-patroon", "ABAB-patroon", "ABBA-patroon", "Geen patroon"], correct: 1, explanation: "Kruisrym volg 'n ABAB-patroon waar elke tweede re\u00ebl rym." },
    { id: 10, unit: "gedigte", type: "mc", question: "Enjambement beteken:", options: ["'n Pouse aan die einde van 'n re\u00ebl", "'n Sin vloei oor na die volgende versre\u00ebl sonder leesteken", "Herhaling van die eerste re\u00ebl", "'n Rympatroon aan die einde van re\u00ebls"], correct: 1, explanation: "Enjambement is wanneer 'n gedagte/sin nie aan die einde van 'n versre\u00ebl eindig nie, maar oorvloei na die volgende re\u00ebl." },
    { id: 11, unit: "gedigte", type: "mc", question: "Die 'toon' (tone) van 'n gedig verwys na:", options: ["Die klankpatroon", "Die digter se houding teenoor die onderwerp", "Die rymskema", "Die aantal strofes"], correct: 1, explanation: "Toon is die digter se houding (attitude) teenoor die onderwerp \u2014 bv. hartseer, ironies, kwaad, speels." },
    { id: 12, unit: "gedigte", type: "mc", question: "Watter formule gebruik jy om gedigvrae in die eksamen te beantwoord?", options: ["Noem + Verduidelik", "Tegniek + Aanhaling + Effek + Tema", "Lees + Skryf + Kontroleer", "Inleiding + Liggaam + Slot"], correct: 1, explanation: "Die formule is: Noem die tegniek, haal aan uit die gedig, verduidelik die effek, en koppel dit aan die tema." },
    { id: 13, unit: "gedigte", type: "mc", question: "'Die donker dae van droogte' is 'n voorbeeld van:", options: ["Personifikasie", "Alliterasie", "Vergelyking", "Enjambement"], correct: 1, explanation: "Dit is alliterasie \u2014 die herhaling van die 'd'-klank aan die begin van opeenvolgende woorde: donker, dae, droogte." },
    { id: 14, unit: "gedigte", type: "mc", question: "'Ek het 'n miljoen keer ges\u00ea' is 'n voorbeeld van:", options: ["Alliterasie", "Personifikasie", "Hiperbool (hyperbole)", "Metafoor"], correct: 2, explanation: "Dit is hiperbool \u2014 'n oordrywing vir effek. Niemand het regtig 'n miljoen keer iets ges\u00ea nie." },
    // --- Skryfwerk ---
    { id: 15, unit: "skryfwerk", type: "mc", question: "Wat is die korrekte aanhef vir 'n formele brief?", options: ["Liewe Mnr. Smit", "Hallo Mnr. Smit", "Geagte Mnr. Smit", "Beste Mnr. Smit"], correct: 2, explanation: "'Geagte' (Dear/Honoured) is die korrekte aanhef vir 'n formele brief. 'Liewe' is vir informele briewe." },
    { id: 16, unit: "skryfwerk", type: "mc", question: "Hoeveel punte word vir 'Inhoud en beplanning' toegeken in skryfwerk?", options: ["15 punte", "20 punte", "30 punte", "50 punte"], correct: 2, explanation: "Inhoud en beplanning tel 30 punte uit 'n totaal van 50. Taal, styl en redigering tel 15, en struktuur tel 5." },
    { id: 17, unit: "skryfwerk", type: "mc", question: "In 'n argumentatiewe opstel, wat is 'n 'teenargument' (counter-argument)?", options: ["Jou hoofargument", "'n Argument wat jou standpunt ondersteun", "'n Argument van die teenoorgestelde kant wat jy dan weerl\u00ea", "Die slot van jou opstel"], correct: 2, explanation: "'n Teenargument is wanneer jy die ander kant se standpunt erken en dit dan weerl\u00ea (rebuttal)." },
    { id: 18, unit: "skryfwerk", type: "mc", question: "Watter groet gebruik jy aan die einde van 'n formele brief?", options: ["Liefde", "Groete", "Die uwe", "Sien jou"], correct: 2, explanation: "'Die uwe' is die formele groet (Yours faithfully/sincerely). 'Liefde' en 'Groete' is informeel." },
    { id: 19, unit: "skryfwerk", type: "mc", question: "Watter verbindingswoord dui op 'n KONTRAS (contrast)?", options: ["Daarom", "Boonop", "Egter (however)", "Aangesien"], correct: 2, explanation: "'Egter' (however) dui op 'n kontras. 'Daarom' = gevolg, 'Boonop' = byvoeging, 'Aangesien' = oorsaak." },
    { id: 20, unit: "skryfwerk", type: "mc", question: "Watter een is NIE 'n kenmerk van beskrywende skryfwerk nie?", options: ["Gebruik van sintuie (senses)", "Skep beelde in die leser se gedagtes", "Neem 'n standpunt in en oortuig die leser", "Gebruik van byvoeglike naamwoorde"], correct: 2, explanation: "Om 'n standpunt in te neem en te oortuig is argumentatiewe skryfwerk, nie beskrywend nie." }
];

// ============================================================
// FEYNMAN TOPICS \u2014 Afrikaans Grade 12 CAPS
// ============================================================
const feynmanTopics = [
    { id: "f1", title: "Leesstrategie\u00eb \u2014 Hoe om 'n Teks te Benader", unit: "begrip", keyPoints: ["Skandeer (scan) vir spesifieke inligting soos name, datums, syfers", "Vlugtig lees (skim) om die hoofgedagte vinnig te kry \u2014 lees eerste en laaste sinne", "Intensiewe lees vir detail en dieper begrip", "Kontekstuele leidrade gebruik om onbekende woorde se betekenis af te lei", "Die hoofgedagte is gewoonlik in die eerste of laaste sin van 'n paragraaf", "Verskillende vraagtipes vereis verskillende antwoordstrategie\u00eb: letterlik, inferensieel, evaluerend"] },
    { id: "f2", title: "Opsommingstegnieke \u2014 Van Teks na Kern", unit: "begrip", keyPoints: ["Lees die teks minstens twee keer deeglik", "Identifiseer en onderstreep hoofpunte (main points) in elke paragraaf", "Laat voorbeelde, herhalings, en onnodige besonderhede weg", "Herformuleer in jou eie woorde (paraphrase)", "Hou by die woordgrens (gewoonlik 70 woorde)", "Skryf in volsinne, een paragraaf, en tel jou woorde"] },
    { id: "f3", title: "Beeldspraak en Digterlike Tegnieke", unit: "gedigte", keyPoints: ["Metafoor: direkte vergelyking sonder 'soos' \u2014 bv. 'Die lewe is 'n reis'", "Vergelyking (simile): gebruik 'soos' of 'net soos' \u2014 bv. 'Sy lag soos 'n klokkie'", "Personifikasie: menslike eienskappe aan nie-menslike dinge \u2014 bv. 'Die wind fluister'", "Alliterasie: herhaling van konsonantklank aan die begin \u2014 bv. 'donker dae van droogte'", "Assonansie: herhaling van vokaalklank binne woorde", "Hiperbool: oordrywing vir effek \u2014 bv. 'Ek het 'n miljoen keer ges\u00ea'"] },
    { id: "f4", title: "Gediganalise \u2014 Hoe om 'n Gedig te Ontleed", unit: "gedigte", keyPoints: ["Lees die gedig minstens 3 keer: vir begrip, vir tegnieke, vir dieper betekenis", "Identifiseer die tema (sentrale boodskap), toon (digter se houding), en bui (leser se gevoel)", "Kyk na woordkeuse (diction) \u2014 hoekom het die digter hierdie spesifieke woorde gekies?", "Identifiseer rymskema (ABAB, AABB, ABBA), enjambement, en strofevorm", "Formule vir antwoorde: Tegniek + Aanhaling + Effek + Tema", "Let op klankeffekte: alliterasie, assonansie, onomatopee"] },
    { id: "f5", title: "Opstelskryfwerk \u2014 Beplanning tot Produk", unit: "skryfwerk", keyPoints: ["Beplan altyd voor jy skryf: brainstorm, mindmap, of lys van idees", "Inleiding: vang aandag met 'n vraag, aanhaling, stelling, of anekdote", "Liggaam: 3\u20135 paragrawe, elk met 'n topiksin, ondersteuning, en slotsin", "Slot: som hoofpunte op, eindig met 'n kragtige slotgedagte", "Gebruik verbindingswoorde om paragrawe en idees te verbind", "Redigeer: lees deur vir spelfoute, taalfoute, en sinstruktuur"] },
    { id: "f6", title: "Briefskryfwerk \u2014 Formeel vs. Informeel", unit: "skryfwerk", keyPoints: ["Formele brief: 'Geagte Mnr./Mev.' + 'Die uwe', volledige adresse, saaklike taal", "Informele brief: 'Liewe [naam]' + 'Liefde/Groete', net jou adres, vriendskaplike taal", "Formele brief het 'n onderwerpreël (subject line)", "Albei benodig: jou adres, datum, aanhef, liggaam, groet, naam", "Formeel: derdepersoonsaanspreekvorm. Informeel: eerste/tweedepersoon", "Toon en register moet by die tipe brief pas"] }
];
