// ============================================================
// FLASHCARD DATA - Mathematics: Functions & Inverses, Euclidean Geometry, Circle Geometry
// ============================================================
const flashcards = [
    // --- Functions & Inverses ---
    { id: 1, unit: "functions", q: "What is the definition of a function?", a: "A function is a relation where every element in the domain (x-value) is mapped to exactly one element in the range (y-value). Each input has only one output." },
    { id: 2, unit: "functions", q: "What is the inverse of a function?", a: "The inverse of a function f is obtained by swapping x and y. If f maps x to y, then f\u207b\u00b9 maps y back to x. Graphically, the inverse is a reflection of f in the line y = x." },
    { id: 3, unit: "functions", q: "How do you find the inverse of y = ax + q (linear function)?", a: "Swap x and y: x = ay + q, then solve for y: y = (x - q)/a. The inverse of a linear function is always a function." },
    { id: 4, unit: "functions", q: "What is the inverse of y = ax\u00b2? Is it a function?", a: "Swap x and y: x = ay\u00b2, so y = \u00b1\u221a(x/a). This is NOT a function because each x-value gives two y-values. You must restrict the domain of the original parabola to make the inverse a function." },
    { id: 5, unit: "functions", q: "How do you restrict the domain of y = ax\u00b2 so that its inverse is a function?", a: "Restrict to either x \u2265 0 (right half) giving inverse y = \u221a(x/a), or x \u2264 0 (left half) giving inverse y = -\u221a(x/a). Each restriction gives one branch of the sideways parabola." },
    { id: 6, unit: "functions", q: "What is the inverse of y = b\u02e3 (exponential function)?", a: "Swap x and y: x = b\u02b8, which gives y = log_b(x). The inverse of an exponential function is a logarithmic function. The inverse is always a function (no restriction needed)." },
    { id: 7, unit: "functions", q: "What is the relationship between exponential and logarithmic functions?", a: "They are inverses of each other. If y = b\u02e3 then x = log_b(y). The graph of y = log_b(x) is the reflection of y = b\u02e3 in the line y = x." },
    { id: 8, unit: "functions", q: "State the key features of y = log_b(x) where b > 1.", a: "Domain: x > 0. Range: y \u2208 \u211d. x-intercept at (1, 0) because log_b(1) = 0. Asymptote: x = 0 (y-axis). The graph increases from left to right. Passes through (b, 1)." },
    { id: 9, unit: "functions", q: "How do the domains and ranges swap between a function and its inverse?", a: "The domain of f becomes the range of f\u207b\u00b9, and the range of f becomes the domain of f\u207b\u00b9. This is because we swap x and y." },
    { id: 10, unit: "functions", q: "What line is the axis of symmetry between a function and its inverse?", a: "The line y = x. A function and its inverse are always reflections of each other in the line y = x." },
    { id: 11, unit: "functions", q: "How do you sketch the inverse of a given graph?", a: "1. Identify key points on the original graph.\n2. Swap the x and y coordinates of each point.\n3. Plot the new points.\n4. Draw the curve through them.\n(Or reflect the entire graph in y = x.)" },
    { id: 12, unit: "functions", q: "What is the inverse of y = 10\u02e3?", a: "y = log\u2081\u2080(x), commonly written as y = log x. The graph passes through (1, 0) and (10, 1), with asymptote x = 0." },

    // --- Euclidean Geometry ---
    { id: 13, unit: "euclidean", q: "State the Proportionality Theorem (Basic Proportionality Theorem).", a: "If a line is drawn parallel to one side of a triangle, it divides the other two sides proportionally. If DE \u2225 BC in \u25b3ABC with D on AB and E on AC, then AD/DB = AE/EC." },
    { id: 14, unit: "euclidean", q: "State the converse of the Proportionality Theorem.", a: "If a line divides two sides of a triangle in the same proportion, then the line is parallel to the third side. If AD/DB = AE/EC, then DE \u2225 BC." },
    { id: 15, unit: "euclidean", q: "State the Midpoint Theorem.", a: "The line segment joining the midpoints of two sides of a triangle is parallel to the third side and equal to half its length. If D and E are midpoints of AB and AC, then DE \u2225 BC and DE = \u00bdBC." },
    { id: 16, unit: "euclidean", q: "What are the conditions for two triangles to be similar?", a: "Two triangles are similar if: (1) All corresponding angles are equal (AAA), OR (2) All corresponding sides are in the same proportion. Similar triangles have the same shape but not necessarily the same size." },
    { id: 17, unit: "euclidean", q: "State the theorem: Triangles with equal bases between parallel lines.", a: "Triangles with equal bases (or the same base) and between the same parallel lines have equal areas. This is because they share the same base and have the same height." },
    { id: 18, unit: "euclidean", q: "If two triangles are equiangular, what can you conclude about their sides?", a: "Their corresponding sides are in proportion (the triangles are similar). This is the AA similarity theorem - if two angles of one triangle equal two angles of another, the triangles are similar." },
    { id: 19, unit: "euclidean", q: "State the Theorem of Pythagoras and its converse.", a: "Theorem: In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides (c\u00b2 = a\u00b2 + b\u00b2).\nConverse: If c\u00b2 = a\u00b2 + b\u00b2 in a triangle, then the angle opposite the longest side is 90\u00b0." },
    { id: 20, unit: "euclidean", q: "Outline the proof of Pythagoras using similar triangles.", a: "In \u25b3ABC with C\u0302 = 90\u00b0, draw altitude CD \u22a5 AB.\n\u25b3ACD ||| \u25b3ABC (AA) \u2192 AC\u00b2 = AD \u00b7 AB\n\u25b3BCD ||| \u25b3ABC (AA) \u2192 BC\u00b2 = BD \u00b7 AB\nAdding: AC\u00b2 + BC\u00b2 = AB(AD + BD) = AB\u00b2. \u220e" },
    { id: 21, unit: "euclidean", q: "How do you prove that two triangles are similar?", a: "Method 1: Show all three pairs of corresponding angles are equal (AAA - only need 2 pairs).\nMethod 2: Show all three pairs of corresponding sides are in the same proportion.\nMethod 3: Show two sides in proportion and included angles equal." },
    { id: 22, unit: "euclidean", q: "What is the area rule relating similar triangles?", a: "If two triangles are similar with sides in ratio k:1, then their areas are in the ratio k\u00b2:1. Area scales as the square of the linear scale factor." },
    { id: 23, unit: "euclidean", q: "Outline the proof of the Proportionality Theorem.", a: "Given DE \u2225 BC. Construct heights from B and C to DE.\nArea(\u25b3ADE)/Area(\u25b3BDE) = AD/DB (same height from E)\nArea(\u25b3ADE)/Area(\u25b3CDE) = AE/EC (same height from D)\n\u25b3BDE and \u25b3CDE have equal areas (same base, between \u2225 lines)\nTherefore AD/DB = AE/EC. \u220e" },
    { id: 24, unit: "euclidean", q: "If \u25b3ABC ||| \u25b3DEF with AB/DE = 3/2 and area of \u25b3ABC = 54 cm\u00b2, find area of \u25b3DEF.", a: "Scale factor k = 3/2, area ratio = k\u00b2 = 9/4.\n54 / Area(\u25b3DEF) = 9/4\nArea(\u25b3DEF) = 54 \u00d7 4/9 = 24 cm\u00b2." },

    // --- Circle Geometry ---
    { id: 25, unit: "circles", q: "State: angle at the centre vs angle at the circumference.", a: "The angle subtended by an arc at the centre is twice the angle subtended by the same arc at any point on the circumference. Central angle = 2 \u00d7 inscribed angle." },
    { id: 26, unit: "circles", q: "State: angles in the same segment.", a: "Angles subtended by the same arc (or chord) at the circumference, on the same side of the chord, are equal." },
    { id: 27, unit: "circles", q: "State: the angle in a semicircle.", a: "The angle subtended by a diameter at the circumference is always 90\u00b0. Special case: central angle is 180\u00b0, so inscribed angle is 90\u00b0." },
    { id: 28, unit: "circles", q: "What is a cyclic quadrilateral?", a: "A four-sided figure with all four vertices on the circumference of a circle." },
    { id: 29, unit: "circles", q: "State: opposite angles of a cyclic quadrilateral.", a: "The opposite angles of a cyclic quadrilateral add up to 180\u00b0 (supplementary). If ABCD is cyclic, then A\u0302 + C\u0302 = 180\u00b0 and B\u0302 + D\u0302 = 180\u00b0." },
    { id: 30, unit: "circles", q: "How do you prove a quadrilateral is cyclic?", a: "(1) Opposite angles are supplementary, OR\n(2) An exterior angle equals the interior opposite angle, OR\n(3) Two points on the same side of a line subtend equal angles to the endpoints." },
    { id: 31, unit: "circles", q: "State the exterior angle theorem for cyclic quadrilaterals.", a: "An exterior angle of a cyclic quadrilateral equals the interior opposite angle." },
    { id: 32, unit: "circles", q: "State the Tangent-Chord (Tan-Chord) theorem.", a: "The angle between a tangent to a circle and a chord drawn from the point of tangency equals the inscribed angle subtended by the chord on the opposite side (angle in alternate segment)." },
    { id: 33, unit: "circles", q: "State the two tangent theorem.", a: "Two tangents drawn from the same external point to a circle are equal in length. The line from the external point to the centre bisects the angle between the tangents." },
    { id: 34, unit: "circles", q: "What is the relationship between a tangent and radius at the point of tangency?", a: "A tangent is perpendicular to the radius at the point of tangency. The angle between them is 90\u00b0." },
    { id: 35, unit: "circles", q: "State: equal chords subtend equal angles.", a: "If two chords are equal in length, they subtend equal angles at the centre. Conversely, chords subtending equal central angles are equal." },
    { id: 36, unit: "circles", q: "State: perpendicular from centre to a chord.", a: "A line from the centre perpendicular to a chord bisects that chord. Conversely, a line from the centre to the midpoint of a chord is perpendicular to the chord." }
];

// ============================================================
// QUIZ QUESTIONS
// ============================================================
const quizQuestions = [
    // --- Functions & Inverses ---
    { id: 1, unit: "functions", type: "mc", question: "What is the inverse of f(x) = 3x - 6?", options: ["f\u207b\u00b9(x) = (x + 6)/3", "f\u207b\u00b9(x) = 3x + 6", "f\u207b\u00b9(x) = (x - 6)/3", "f\u207b\u00b9(x) = -3x + 6"], correct: 0, explanation: "Swap x and y: x = 3y - 6, then x + 6 = 3y, so y = (x + 6)/3." },
    { id: 2, unit: "functions", type: "mc", question: "The graph of y = log\u2083(x) passes through which point?", options: ["(0, 1)", "(1, 0)", "(3, 0)", "(0, 3)"], correct: 1, explanation: "log\u2083(1) = 0, so the graph passes through (1, 0). All log graphs pass through (1, 0)." },
    { id: 3, unit: "functions", type: "mc", question: "The inverse of y = 2\u02e3 is:", options: ["y = x\u00b2", "y = 2\u207b\u02e3", "y = log\u2082(x)", "y = \u221ax"], correct: 2, explanation: "Swap x and y: x = 2\u02b8 \u2192 y = log\u2082(x). The inverse of an exponential is a logarithm with the same base." },
    { id: 4, unit: "functions", type: "mc", question: "The inverse of y = x\u00b2 (unrestricted domain) is NOT a function because:", options: ["It has no y-intercept", "It fails the vertical line test", "It is not continuous", "It has no domain"], correct: 1, explanation: "y = \u00b1\u221ax fails the vertical line test since each positive x gives two y-values." },
    { id: 5, unit: "functions", type: "mc", question: "If f(x) = x\u00b2 with domain x \u2265 0, the inverse is:", options: ["f\u207b\u00b9(x) = -\u221ax", "f\u207b\u00b9(x) = \u221ax", "f\u207b\u00b9(x) = \u00b1\u221ax", "f\u207b\u00b9(x) = x\u00b2"], correct: 1, explanation: "Restricting to x \u2265 0 gives inverse f\u207b\u00b9(x) = \u221ax (positive root only)." },
    { id: 6, unit: "functions", type: "mc", question: "A function and its inverse are reflections in:", options: ["y = 0", "x = 0", "y = x", "y = -x"], correct: 2, explanation: "A function and its inverse are always reflections in the line y = x." },

    // --- Euclidean Geometry ---
    { id: 7, unit: "euclidean", type: "mc", question: "In \u25b3ABC, DE \u2225 BC. If AD = 4, DB = 6, AE = 3, find EC.", options: ["2", "4.5", "5", "7.5"], correct: 1, explanation: "Proportionality Theorem: AD/DB = AE/EC \u2192 4/6 = 3/EC \u2192 EC = 4.5." },
    { id: 8, unit: "euclidean", type: "mc", question: "The Midpoint Theorem states the line joining midpoints of two sides of a triangle is:", options: ["Equal to the third side", "Parallel to the third side and half its length", "Perpendicular to the third side", "Twice the third side"], correct: 1, explanation: "The segment joining midpoints is parallel to the third side and half its length." },
    { id: 9, unit: "euclidean", type: "mc", question: "Two triangles are similar if:", options: ["They have the same perimeter", "Their corresponding angles are all equal", "They share one side", "One is inside the other"], correct: 1, explanation: "Triangles are similar if all corresponding angles are equal (AAA)." },
    { id: 10, unit: "euclidean", type: "mc", question: "In the Pythagoras proof using similar triangles, the altitude is drawn from:", options: ["A vertex to the midpoint of the opposite side", "The right angle to the hypotenuse", "An acute angle to the opposite side", "The centre of the hypotenuse"], correct: 1, explanation: "The altitude from the right angle to the hypotenuse creates two smaller triangles each similar to the original." },
    { id: 11, unit: "euclidean", type: "mc", question: "If similar triangles have scale factor 3:1, the ratio of their areas is:", options: ["3:1", "6:1", "9:1", "27:1"], correct: 2, explanation: "Areas scale as the square of the linear factor: 3\u00b2:1\u00b2 = 9:1." },

    // --- Circle Geometry ---
    { id: 12, unit: "circles", type: "mc", question: "The angle at the centre is _____ the angle at the circumference.", options: ["Equal to", "Twice", "Half", "Three times"], correct: 1, explanation: "Central angle = 2 \u00d7 inscribed angle." },
    { id: 13, unit: "circles", type: "mc", question: "The angle in a semicircle is always:", options: ["45\u00b0", "60\u00b0", "90\u00b0", "180\u00b0"], correct: 2, explanation: "Diameter subtends 180\u00b0 at centre, so inscribed angle = 90\u00b0." },
    { id: 14, unit: "circles", type: "mc", question: "Opposite angles of a cyclic quadrilateral:", options: ["Are equal", "Add up to 90\u00b0", "Add up to 180\u00b0", "Add up to 360\u00b0"], correct: 2, explanation: "Opposite angles of a cyclic quadrilateral are supplementary (180\u00b0)." },
    { id: 15, unit: "circles", type: "mc", question: "A tangent to a circle is _____ to the radius at the point of tangency.", options: ["Parallel", "Perpendicular", "Equal", "Bisected by"], correct: 1, explanation: "A tangent is perpendicular (90\u00b0) to the radius at the point of tangency." },
    { id: 16, unit: "circles", type: "mc", question: "The tan-chord angle equals:", options: ["The angle at the centre", "The angle in the alternate segment", "Twice the inscribed angle", "Half the reflex angle"], correct: 1, explanation: "The tangent-chord angle equals the inscribed angle in the alternate segment." },
    { id: 17, unit: "circles", type: "mc", question: "Two tangents from the same external point are:", options: ["Perpendicular", "Parallel", "Equal in length", "Unequal"], correct: 2, explanation: "Two tangents from the same external point are always equal in length." },
    { id: 18, unit: "circles", type: "mc", question: "If ABCD is cyclic and A\u0302 = 70\u00b0, then C\u0302 = ?", options: ["70\u00b0", "90\u00b0", "110\u00b0", "140\u00b0"], correct: 2, explanation: "Opposite angles supplementary: A\u0302 + C\u0302 = 180\u00b0 \u2192 C\u0302 = 110\u00b0." },
    { id: 19, unit: "circles", type: "mc", question: "An exterior angle of a cyclic quadrilateral equals:", options: ["The adjacent interior angle", "The interior opposite angle", "Half the central angle", "The sum of all interior angles"], correct: 1, explanation: "Exterior angle of a cyclic quad = interior opposite angle." },
    { id: 20, unit: "circles", type: "mc", question: "The perpendicular from the centre to a chord:", options: ["Passes through a vertex", "Bisects the chord", "Equals the radius", "Is parallel to the tangent"], correct: 1, explanation: "A perpendicular from the centre to a chord bisects that chord." }
];

// ============================================================
// FEYNMAN TOPICS
// ============================================================
const feynmanTopics = [
    { id: "f1", title: "Inverse of a Parabola (y = ax\u00b2)", unit: "functions", keyPoints: ["Swap x and y: x = ay\u00b2 \u2192 y = \u00b1\u221a(x/a)", "The inverse is NOT a function (fails vertical line test)", "Restrict domain: x \u2265 0 gives y = \u221a(x/a), x \u2264 0 gives y = -\u221a(x/a)", "Graphically: sideways parabola, reflection in y = x", "Restricted inverse domain x \u2265 0 (if a > 0), range y \u2265 0 or y \u2264 0"] },
    { id: "f2", title: "Exponential and Logarithmic Functions as Inverses", unit: "functions", keyPoints: ["y = b\u02e3 and y = log_b(x) are inverses of each other", "Exponential: domain \u211d, range y > 0, asymptote y = 0, passes through (0, 1)", "Logarithmic: domain x > 0, range \u211d, asymptote x = 0, passes through (1, 0)", "Domains and ranges swap because x and y are swapped", "For b > 1 both increase; for 0 < b < 1 both decrease", "log_b(b\u02e3) = x and b^(log_b(x)) = x"] },
    { id: "f3", title: "Sketching Inverses and Reading from Graphs", unit: "functions", keyPoints: ["Reflect original graph in y = x", "Swap coordinates: (a, b) becomes (b, a)", "x-intercept of f becomes y-intercept of f\u207b\u00b9", "Horizontal asymptote becomes vertical asymptote", "Domain of f becomes range of f\u207b\u00b9", "Function and inverse intersect on y = x"] },
    { id: "f4", title: "The Proportionality Theorem and Its Proof", unit: "euclidean", keyPoints: ["If DE \u2225 BC in \u25b3ABC, then AD/DB = AE/EC", "Proof uses area ratios: same-height triangles have areas proportional to bases", "Construct heights from B and C to line DE", "\u25b3BDE and \u25b3CDE have equal areas (same base, between parallel lines)", "Therefore Area(\u25b3ADE)/Area(\u25b3BDE) = Area(\u25b3ADE)/Area(\u25b3CDE)", "Giving AD/DB = AE/EC"] },
    { id: "f5", title: "Similar Triangles \u2014 Proving and Using Similarity", unit: "euclidean", keyPoints: ["Similar if corresponding angles equal (AAA \u2014 need only 2 angles)", "Or corresponding sides in same proportion", "Write similarity with vertices in corresponding order: \u25b3ABC ||| \u25b3DEF", "Once similar: use proportional sides to find unknowns", "Area ratio = (length ratio)\u00b2"] },
    { id: "f6", title: "Theorem of Pythagoras \u2014 Similar Triangles Proof", unit: "euclidean", keyPoints: ["\u25b3ABC with C\u0302 = 90\u00b0; draw altitude CD \u22a5 AB", "Creates 3 similar triangles: \u25b3ABC, \u25b3ACD, \u25b3CBD", "\u25b3ACD ||| \u25b3ABC: AC\u00b2 = AD \u00b7 AB", "\u25b3BCD ||| \u25b3ABC: BC\u00b2 = BD \u00b7 AB", "Add: AC\u00b2 + BC\u00b2 = AB(AD + BD) = AB\u00b2", "Elegant proof using only similar triangle properties"] },
    { id: "f7", title: "Angle at Centre vs Angle at Circumference", unit: "circles", keyPoints: ["Central angle = 2 \u00d7 inscribed angle (same arc)", "Special case: semicircle \u2192 inscribed angle = 90\u00b0", "Angles in same segment are equal (both half of same central angle)", "Central angle equals the arc it subtends", "Foundation for all other circle theorems"] },
    { id: "f8", title: "Cyclic Quadrilaterals \u2014 Properties and Proofs", unit: "circles", keyPoints: ["All four vertices on the circle", "Opposite angles supplementary (sum to 180\u00b0)", "Proof: opposite angles subtend arcs totalling 360\u00b0, so central angles sum to 360\u00b0, inscribed angles sum to 180\u00b0", "Exterior angle = interior opposite angle", "Prove cyclic: opposite angles supplementary, or ext = int opp, or equal angles from same segment"] },
    { id: "f9", title: "Tangent Properties and the Tan-Chord Theorem", unit: "circles", keyPoints: ["Tangent \u22a5 radius at point of tangency (90\u00b0)", "Two tangents from same external point are equal", "Tan-chord angle = angle in alternate segment", "Use tan-chord to find unknown angles with tangent lines", "Tangent-radius perpendicularity key for Pythagoras calculations"] }
];
